version: "3"
services:
  db:
    image: "postgres:11"
    environment:
      POSTGRES_PASSWORD: "secretPassword"
      POSTGRES_USER: "vivaLaLita"
      POSTGRES_DB: "vivaLaLitaDB"

    container_name: "my_postgres"
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata: